# Generated by Django 2.2.5 on 2019-09-09 11:26
import os
from django.db import migrations
from authapi.models import User

def forwards_func(apps, schema_editor):
  # build the user you now have access to via Django magic
    User.objects.create_superuser('admin', os.getenv('ADMIN_PASSWORD'))

def reverse_func(apps, schema_editor):
    # destroy what forward_func builds
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
